Add the libedit package explicitly
thaJeztah/pgadmin4-docker pull request #37
Opened 2018-07-26 15:53 UTC by alsin

So that psql does not fail when running a COPY .. FROM on a CSV file

Fixes #36

2018-07-26 15:57 UTC, alsin commented
I've concatenated two RUN statements into one single to reduce number of layers. Tested on machine, importing CSVs now works.

2018-11-28 14:46 UTC, chrisob commented
@thaJeztah Any thoughts on this PR?

2019-01-16 07:12 UTC, DoryZi commented
Any clue what's going on with this??

2019-01-16 13:29 UTC, thaJeztah requested changes
thanks @alsin ! I left a comment below; currently working on tagging some new versions of this image, so I'll carry your change to move fast, and to add the `libedit` package 🤗

2019-01-16 13:29 UTC, thaJeztah commented on Dockerfile
> -RUN apk add --no-cache alpine-sdk postgresql-dev \
I don't think we should combine these steps; having these layers separate improves caching (when building the image), and allows image layers to be shared (if you have multiple versions of this image).

Given that there's no overlap between the two steps, combining the layers won't make the image smaller;

```
REPOSITORY   TAG        IMAGE ID            CREATED             SIZE
pgadmin4     libedit    6a52eb68dd5e        7 seconds ago       243MB
pgadmin4     latest     f188f718d788        3 minutes ago       243MB
```

2019-01-16 13:31 UTC, closed without merging